monolog:
  channels: ['tinect_matomo']

  handlers:
    tinectMatomoLogHandler:
      type: rotating_file
      path: "%kernel.logs_dir%/tinect_matomo_%kernel.environment%.log"
      level: info
      max_files: 30
      channels: [ 'tinect_matomo' ]
